build: improved portability -- auto detection of RISC-V -march (+v)
Before:
march was explicitly set to rv64imafd(v) for check of vector support.
This restricted support for many platforms (e.g 32bit RISC-V).

Now:
 * determine march from given compiler configuration or CFLAGS
 * check vector support:
   * if v is missing in march, add it and try build -> on success add
     march+v to assembler and compiler flags
   * if v is not missing, still try the build as paranoia check

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8,6 +8,13 @@
 RVVBMARK_INSTALL_PREFIX="/usr/local"
 RVVBMARK_RV_SUPPORT=0
 RVVBMARK_RVV_SUPPORT=0
+RVVBMARK_EXTRA_ASFLAGS=""
+RVVBMARK_EXTRA_CFLAGS=""
+
+
+# set defaults if not set
+[[ -z $CC ]] && CC=gcc
+[[ -z $AS ]] && AS=as
 
 
 usage()
@@ -28,6 +35,18 @@ Installation directories:
 
 _ACEOF
 }
+
+# try to get flags given by name from CFLAGS xor CC
+# $1 .. flagname
+getflag()
+{
+	value=$(echo $CFLAGS | grep "$1" | sed -e 's/.*$1=\([[:alnum:]]*\).*/\1/g')
+	[[ -z $value ]] && \
+		value=$($CC -### -E - 2>&1 | grep "$1" | head -n 1 | sed -e "s/.*-$1=\([[:alnum:]]*\).*/\1/g")
+	echo $value
+}
+
+
 
 args=$(getopt -o h --long help,prefix: -- "$@")
 if [[ $? -ne 0 ]] ; then
@@ -69,25 +88,50 @@ else
 fi
 
 echo -en "Check toolchain RISC-V support .. "
-if $AS bmark_memcpy_rv.s -o /dev/null > /dev/null 2>&1 ; then
+if ! $AS bmark_memcpy_rv.s -o /dev/null > /dev/null 2>&1 ; then
+	echo "no"
+
+else
 	echo "yes"
 	RVVBMARK_RV_SUPPORT=1
-else
-	echo "no"
+
+	echo -en "Check toolchain RISC-V vector support .. "
+	march=$(getflag march)
+	if [[ -z $march ]] ; then
+		echo "no (unable to determine march)"
+
+	else
+		# add v if not included in march_tmp
+		march_tmp=$march
+		[[ $march != rv*v* ]] && march_tmp+=v
+
+		# try build
+		if $AS -march=$march_tmp bmark_memcpy_rvv.s -o /dev/null > /dev/null 2>&1 ; then
+			RVVBMARK_RVV_SUPPORT=1
+
+			# override march in flags, if v was added above
+			if [[ $march != $march_tmp ]] ; then
+				echo "yes (added v to -march=($march_tmp))"
+				RVVBMARK_EXTRA_ASFLAGS+="-march=$march_tmp"
+				RVVBMARK_EXTRA_CFLAGS+="-march=$march_tmp"
+			else
+				echo "yes"
+			fi
+		else
+			echo "no (unable to build)"
+		fi
+
+	fi
 fi
 
-echo -en "Check toolchain RISC-V vector (rv64imafdcv) support .. "
-if $AS -march=rv64imafdcv bmark_memcpy_rvv.s -o /dev/null > /dev/null 2>&1 ; then
-	echo "yes"
-	RVVBMARK_RVV_SUPPORT=1
-else
-	echo "no"
-fi
+
 
 sed config.mk.in							\
 	-e s#\@RVVBMARK_RV_SUPPORT\@#$RVVBMARK_RV_SUPPORT#g		\
 	-e s#\@RVVBMARK_RVV_SUPPORT\@#$RVVBMARK_RVV_SUPPORT#g		\
 	-e s#\@RVVBMARK_INSTALL_PREFIX\@#$RVVBMARK_INSTALL_PREFIX#g	\
+	-e s#\@RVVBMARK_EXTRA_ASFLAGS\@#$RVVBMARK_EXTRA_ASFLAGS#g	\
+	-e s#\@RVVBMARK_EXTRA_CFLAGS\@#$RVVBMARK_EXTRA_CFLAGS#g		\
 	> config.mk
 
 echo "done."
